name: DeathArena
main: DeathArena.DeathArenaMain
version: 0.1
commands:
    class:
        usage:
        description: Chooses a class.
    saveplayer:
        usage:
        description: Command to test saving player configs.
    loadedit:
        usage:
        description: Command to test loading/editing/saving of player configs.